platform :ios, '8.0'

use_frameworks!

target 'MoyaNetworkClient_Example' do
  pod 'MoyaNetworkClient', :path => '../'
  pod 'MoyaNetworkClient/Cache', :path => '../'
  pod 'MoyaNetworkClient/Future', :path => '../'
end
