# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage


osx_image: xcode10.3
xcode_destination: platform=iOS Simulator,OS=11.3,name=iPhone X
xcode_project: Example/MoyaNetworkClient.xcworkspace
xcode_scheme: MoyaNetworkClient-Example
language: swift
cache: cocoapods
env:
  global:
  - WORKSPACE=Example/MoyaNetworkClient.xcworkspace
  - IOS_FRAMEWORK_SCHEME="MoyaNetworkClient"
  - EXAMPLE_SCHEME="MoyaNetworkClient-Example"
  matrix:
    - DESTINATION="OS=11.3,name=iPhone X"          SCHEME="$IOS_FRAMEWORK_SCHEME"      RUN_TESTS="YES" BUILD_EXAMPLE="YES" POD_LINT="YES"
    - DESTINATION="OS=10.3.1,name=iPhone 7 Plus"   SCHEME="$IOS_FRAMEWORK_SCHEME"      RUN_TESTS="YES" BUILD_EXAMPLE="YES" POD_LINT="NO"
podfile: Example/Podfile
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod repo update --silent
- pod install --project-directory=Example
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty;
  - pod lib lint
